---
title: "SOA Research Cost Simulation"
output: pdf_document
date: "2023-03-16"
---

```{r setup, include=FALSE}
library(readr)
library(evd)
library(fitdistrplus)
library(actuar)
library(goftest)
library(ParetoPosStable)
library(univariateML)
```

```{r DATA, include=FALSE}
DATA=read_csv("DATA.csv")
DATA=DATA[order(DATA$Quarter),]
DATA=DATA[order(DATA$Year),]

Inflation_adjusted_damages=read_csv("yearafter1960.csv")
Inflation_adjusted_damages=Inflation_adjusted_damages[order(Inflation_adjusted_damages$Quarter),]
Inflation_adjusted_damages=Inflation_adjusted_damages[order(Inflation_adjusted_damages$Year),]

Inflation_adjusted_damages$Presentvalue
minor_cost=Inflation_adjusted_damages[Inflation_adjusted_damages$Presentvalue<15000,]
medium_cost=Inflation_adjusted_damages[Inflation_adjusted_damages$Presentvalue>15000 
                                       & Inflation_adjusted_damages$Presentvalue<6000000,]
major_cost=Inflation_adjusted_damages[Inflation_adjusted_damages$Presentvalue>6000000,]

```

```{r Claim Amount lambda ARIMA}
#####################################ARIMA HERE

lambda_medium_SSP5=17.106*1.17750^(1:10/10)
lambda_major_SSP5=2.55484*1.17750^(1:10/10)

lambda_medium_SSP3=17.106*1.15665^(1:10/10)
lambda_major_SSP3=2.55484*1.15665^(1:10/10)

lambda_medium_SSP2=17.106*1.12346^(1:10/10)
lambda_major_SSP2=2.55484*1.12346^(1:10/10)

lambda_medium_SSP1=17.106*1.10890^(1:10/10)
lambda_major_SSP1=2.55484*1.10890^(1:10/10)
#expected_yearly_damage=(2.25*mean(major_cost$Presentvalue)*lambda_major+1.25*mean(medium_cost$Presentvalue)*lambda_medium)
```


```{r Claim Cost distribution fitting medium}
lnorm_med_fit=mllnorm(medium_cost$Presentvalue)
pareto_med_fit=mlpareto(medium_cost$Presentvalue)
gamma_med_fit=univariateML::mlgamma(medium_cost$Presentvalue)
invgauss_med_fit=mlinvgauss(medium_cost$Presentvalue)

{plot(ecdf(medium_cost$Presentvalue))
lines(ecdf(rlnorm(10000,lnorm_med_fit[1],lnorm_med_fit[2])),col="green")
lines(ecdf(rpareto(10000,pareto_med_fit[1],pareto_med_fit[2])),col="red")
lines(ecdf(rgamma(10000,gamma_med_fit[1],gamma_med_fit[2])),col="blue")
lines(ecdf(rinvgauss(10000,invgauss_med_fit[1],invgauss_med_fit[2])),col="purple")
}

ad.test(medium_cost$Presentvalue,"plnorm",meanlog=lnorm_med_fit[1],sdlog=lnorm_med_fit[2])
ad.test(medium_cost$Presentvalue,"ppareto",shape=pareto_med_fit[1],scale=pareto_med_fit[2])
ad.test(medium_cost$Presentvalue,"pgamma",shape=gamma_med_fit[1],rate=gamma_med_fit[2])
ad.test(medium_cost$Presentvalue,"pinvgauss",mean=invgauss_med_fit[1],shape=invgauss_med_fit[2])

cvm.test(medium_cost$Presentvalue,"plnorm",meanlog=lnorm_med_fit[1],sdlog=lnorm_med_fit[2])
cvm.test(medium_cost$Presentvalue,"ppareto",shape=pareto_med_fit[1],scale=pareto_med_fit[2])
cvm.test(medium_cost$Presentvalue,"pgamma",shape=gamma_med_fit[1],rate=gamma_med_fit[2])
cvm.test(medium_cost$Presentvalue,"pinvgauss",mean=invgauss_med_fit[1],shape=invgauss_med_fit[2])
```

```{r Claim Cost distribution fitting major}
weibull_maj_fit=mlweibull(major_cost$Presentvalue)
pareto_maj_fit=mlpareto(major_cost$Presentvalue)
lgamma_maj_fit=mllgamma(major_cost$Presentvalue)

{plot(ecdf(major_cost$Presentvalue))
lines(ecdf(rweibull(10000,weibull_maj_fit[1],weibull_maj_fit[2])),col="red") #mean=108,960,581
lines(ecdf(rlgamma(100000,lgamma_maj_fit[1],lgamma_maj_fit[2])),col="green") #mean=65,903,627
lines(ecdf(rpareto(10000,pareto_maj_fit[1],pareto_maj_fit[2])),col="blue") #mean=513,638,478
lines(ecdf(rinvgauss(10000,invgauss_maj_fit[1],invgauss_maj_fit[2])),col="orange") #225247481
lines(ecdf(rlnorm(10000,lnorm_maj_fit[1],lnorm_maj_fit[2])),col="purple")
}

ad.test(major_cost$Presentvalue,"pweibull",shape=weibull_maj_fit[1],scale=weibull_maj_fit[2])
ad.test(major_cost$Presentvalue,"ppareto",shape=pareto_maj_fit[1],scale=pareto_maj_fit[2])
ad.test(major_cost$Presentvalue,"plgamma",shapelog=lgamma_maj_fit[1],ratelog=lgamma_maj_fit[2])

cvm.test(major_cost$Presentvalue,"pweibull",shape=weibull_maj_fit[1],scale=weibull_maj_fit[2])
cvm.test(major_cost$Presentvalue,"ppareto",shape=pareto_maj_fit[1],scale=pareto_maj_fit[2])
cvm.test(major_cost$Presentvalue,"plgamma",shapelog=lgamma_maj_fit[1],ratelog=lgamma_maj_fit[2])


```

```{r Loss Simulation SSP5}
n=100000
stopping_time=10
count=0
yearlyloss=matrix(rep(0,(stopping_time+1)*n),nrow=stopping_time+1,ncol=n)
for(i in 1:stopping_time){
  yearlyloss[i+1,]=yearlyloss[i+1,]+yearlyloss[i,]
  for(j in 1:n){
    N_med=rpois(1,lambda_medium_SSP5[i])
    N_maj=rpois(1,lambda_major_SSP5[i])
    if(N_med>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(1.25*rinvgauss(N_med,invgauss_med_fit[1],invgauss_med_fit[2]))
    } 
    if(N_maj>0){
      temp_maj_cost=sum(2.25*rlgamma(N_maj,lgamma_maj_fit[1],lgamma_maj_fit[2]))
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+temp_maj_cost+temp_maj_cost/median_house_price*2.5*1857.908671*12
    }
  }
}
quantile99_SSP5=rep(0,stopping_time+1)
quantile95_SSP5=rep(0,stopping_time+1)
quantile50_SSP5=rep(0,stopping_time+1)
quantile5_SSP5=rep(0,stopping_time+1)
quantile1_SSP5=rep(0,stopping_time+1)
sim_mean_SSP5=rep(0,stopping_time+1)
for(k in 1:(stopping_time+1)){
  quantile99_SSP5[k]=quantile(yearlyloss[k,],0.99)
  quantile95_SSP5[k]=quantile(yearlyloss[k,],0.95)
  quantile50_SSP5[k]=quantile(yearlyloss[k,],0.5)
  quantile5_SSP5[k]=quantile(yearlyloss[k,],0.05)
  quantile1_SSP5[k]=quantile(yearlyloss[k,],0.01)
  sim_mean_SSP5[k]=mean(yearlyloss[k,])
}
mean_damage=rep(0,11)
for(i in 1:10){
  mean_damage[i+1]=sum(expected_yearly_damage[1:i])
}

{plot(2020:2030,quantile99_SSP5,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
polygon(c(2020:2030,2030:2020),c(quantile99_SSP5,rev(quantile95_SSP5)),col="lightcoral",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile95_SSP5,rev(quantile50_SSP5)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile50_SSP5,rev(quantile5_SSP5)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile5_SSP5,rev(quantile1_SSP5)),col="lightcoral",border = "white")
#lines(2020:2030,mean_damage,type="l",lwd=4,col="blue")
lines(2020:2030,quantile99_SSP5,type="l",lwd=2)
lines(2020:2030,quantile95_SSP5,type="l",lwd=2)
lines(2020:2030,quantile50_SSP5,type="l",lwd=2)
lines(2020:2030,quantile5_SSP5,type="l",lwd=2)
lines(2020:2030,quantile1_SSP5,type="l",lwd=2)
lines(2020:2030,sim_mean_SSP5,type="l",lwd=4,col="blue")
}
quantile99_SSP5
sim_mean_SSP5
```

```{r Loss Simulation SSP3}
n=100000
stopping_time=10
count=0
yearlyloss=matrix(rep(0,(stopping_time+1)*n),nrow=stopping_time+1,ncol=n)
for(i in 1:stopping_time){
  yearlyloss[i+1,]=yearlyloss[i+1,]+yearlyloss[i,]
  for(j in 1:n){
    N_med=rpois(1,lambda_medium_SSP3[i])
    N_maj=rpois(1,lambda_major_SSP3[i])
    if(N_med>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(1.25*rinvgauss(N_med,invgauss_med_fit[1],invgauss_med_fit[2]))
    } 
    if(N_maj>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(2.25*rlgamma(N_maj,lgamma_maj_fit[1],lgamma_maj_fit[2]))
    }
  }
}
quantile99_SSP3=rep(0,stopping_time+1)
quantile95_SSP3=rep(0,stopping_time+1)
quantile50_SSP3=rep(0,stopping_time+1)
quantile5_SSP3=rep(0,stopping_time+1)
quantile1_SSP3=rep(0,stopping_time+1)
sim_mean_SSP3=rep(0,stopping_time+1)
for(k in 1:(stopping_time+1)){
  quantile99_SSP3[k]=quantile(yearlyloss[k,],0.99)
  quantile95_SSP3[k]=quantile(yearlyloss[k,],0.95)
  quantile50_SSP3[k]=quantile(yearlyloss[k,],0.5)
  quantile5_SSP3[k]=quantile(yearlyloss[k,],0.05)
  quantile1_SSP3[k]=quantile(yearlyloss[k,],0.01)
  sim_mean_SSP3[k]=mean(yearlyloss[k,])
}
mean_damage=rep(0,11)
for(i in 1:10){
  mean_damage[i+1]=sum(expected_yearly_damage[1:i])
}

{plot(2020:2030,quantile99_SSP3,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
polygon(c(2020:2030,2030:2020),c(quantile99_SSP3,rev(quantile95_SSP3)),col="lightcoral",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile95_SSP3,rev(quantile50_SSP3)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile50_SSP3,rev(quantile5_SSP3)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile5_SSP3,rev(quantile1_SSP3)),col="lightcoral",border = "white")
#lines(2020:2030,mean_damage,type="l",lwd=4,col="blue")
lines(2020:2030,quantile99_SSP3,type="l",lwd=2)
lines(2020:2030,quantile95_SSP3,type="l",lwd=2)
lines(2020:2030,quantile50_SSP3,type="l",lwd=2)
lines(2020:2030,quantile5_SSP3,type="l",lwd=2)
lines(2020:2030,quantile1_SSP3,type="l",lwd=2)
lines(2020:2030,sim_mean_SSP3,type="l",lwd=4,col="blue")
}
quantile99_SSP3
sim_mean_SSP3
```

```{r Loss Simulation SSP2}
n=100000
stopping_time=10
count=0
yearlyloss=matrix(rep(0,(stopping_time+1)*n),nrow=stopping_time+1,ncol=n)
for(i in 1:stopping_time){
  yearlyloss[i+1,]=yearlyloss[i+1,]+yearlyloss[i,]
  for(j in 1:n){
    N_med=rpois(1,lambda_medium_SSP2[i])
    N_maj=rpois(1,lambda_major_SSP2[i])
    if(N_med>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(1.25*rinvgauss(N_med,invgauss_med_fit[1],invgauss_med_fit[2]))
    } 
    if(N_maj>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(2.25*rlgamma(N_maj,lgamma_maj_fit[1],lgamma_maj_fit[2]))
    }
  }
}
quantile99_SSP2=rep(0,stopping_time+1)
quantile95_SSP2=rep(0,stopping_time+1)
quantile50_SSP2=rep(0,stopping_time+1)
quantile5_SSP2=rep(0,stopping_time+1)
quantile1_SSP2=rep(0,stopping_time+1)
sim_mean_SSP2=rep(0,stopping_time+1)
for(k in 1:(stopping_time+1)){
  quantile99_SSP2[k]=quantile(yearlyloss[k,],0.99)
  quantile95_SSP2[k]=quantile(yearlyloss[k,],0.95)
  quantile50_SSP2[k]=quantile(yearlyloss[k,],0.5)
  quantile5_SSP2[k]=quantile(yearlyloss[k,],0.05)
  quantile1_SSP2[k]=quantile(yearlyloss[k,],0.01)
  sim_mean_SSP2[k]=mean(yearlyloss[k,])
}
mean_damage=rep(0,11)
for(i in 1:10){
  mean_damage[i+1]=sum(expected_yearly_damage[1:i])
}

{plot(2020:2030,quantile99_SSP2,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
polygon(c(2020:2030,2030:2020),c(quantile99_SSP2,rev(quantile95_SSP2)),col="lightcoral",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile95_SSP2,rev(quantile50_SSP2)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile50_SSP2,rev(quantile5_SSP2)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile5_SSP2,rev(quantile1_SSP2)),col="lightcoral",border = "white")
#lines(2020:2030,mean_damage,type="l",lwd=4,col="blue")
lines(2020:2030,quantile99_SSP2,type="l",lwd=2)
lines(2020:2030,quantile95_SSP2,type="l",lwd=2)
lines(2020:2030,quantile50_SSP2,type="l",lwd=2)
lines(2020:2030,quantile5_SSP2,type="l",lwd=2)
lines(2020:2030,quantile1_SSP2,type="l",lwd=2)
lines(2020:2030,sim_mean_SSP2,type="l",lwd=4,col="blue")
}
quantile99_SSP2
sim_mean_SSP2
```

```{r Loss Simulation SSP1}
n=100000
stopping_time=10
count=0
yearlyloss=matrix(rep(0,(stopping_time+1)*n),nrow=stopping_time+1,ncol=n)
for(i in 1:stopping_time){
  yearlyloss[i+1,]=yearlyloss[i+1,]+yearlyloss[i,]
  for(j in 1:n){
    N_med=rpois(1,lambda_medium_SSP1[i])
    N_maj=rpois(1,lambda_major_SSP1[i])
    if(N_med>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(1.25*rinvgauss(N_med,invgauss_med_fit[1],invgauss_med_fit[2]))
    } 
    if(N_maj>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(2.25*rlgamma(N_maj,lgamma_maj_fit[1],lgamma_maj_fit[2]))
    }
  }
}
quantile99_SSP1=rep(0,stopping_time+1)
quantile95_SSP1=rep(0,stopping_time+1)
quantile50_SSP1=rep(0,stopping_time+1)
quantile5_SSP1=rep(0,stopping_time+1)
quantile1_SSP1=rep(0,stopping_time+1)
sim_mean_SSP1=rep(0,stopping_time+1)
for(k in 1:(stopping_time+1)){
  quantile99_SSP1[k]=quantile(yearlyloss[k,],0.99)
  quantile95_SSP1[k]=quantile(yearlyloss[k,],0.95)
  quantile50_SSP1[k]=quantile(yearlyloss[k,],0.5)
  quantile5_SSP1[k]=quantile(yearlyloss[k,],0.05)
  quantile1_SSP1[k]=quantile(yearlyloss[k,],0.01)
  sim_mean_SSP1[k]=mean(yearlyloss[k,])
}
mean_damage=rep(0,11)
for(i in 1:10){
  mean_damage[i+1]=sum(expected_yearly_damage[1:i])
}

{plot(2020:2030,quantile99_SSP1,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
polygon(c(2020:2030,2030:2020),c(quantile99_SSP1,rev(quantile95_SSP1)),col="lightcoral",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile95_SSP1,rev(quantile50_SSP1)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile50_SSP1,rev(quantile5_SSP1)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile5_SSP1,rev(quantile1_SSP1)),col="lightcoral",border = "white")
#lines(2020:2030,mean_damage,type="l",lwd=4,col="blue")
lines(2020:2030,quantile99_SSP1,type="l",lwd=2)
lines(2020:2030,quantile95_SSP1,type="l",lwd=2)
lines(2020:2030,quantile50_SSP1,type="l",lwd=2)
lines(2020:2030,quantile5_SSP1,type="l",lwd=2)
lines(2020:2030,quantile1_SSP1,type="l",lwd=2)
lines(2020:2030,sim_mean_SSP1,type="l",lwd=4,col="blue")
}
quantile99_SSP1
sim_mean_SSP1
```

```{r Cost plotting}
{
plot(2020:2030,quantile50_SSP1,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
lines(2020:2030,quantile50_SSP2,col="red")
lines(2020:2030,quantile50_SSP3,col="blue")
lines(2020:2030,quantile50_SSP5,col="green")
}

```


```{r %Relocation}
household_at_risk=0.01*18379116/2.5
median_house_price=200000#205120.0939
Percent_relocated=0.30*0.8^(1:10)+0.7 #AMOUNT WE CAN MITIGATE USING VOLUNTARY RELOCATION
Percent_relocated=c(1,Percent_relocated)
flooding_maj_percent=0.3006
flooding_med_percent=0.1713
lambda_major_SSP5
lambda_major_SSP5_relocation=lambda_major_SSP5*(Percent_relocated[-1]*flooding_maj_percent+(1-flooding_maj_percent))
lambda_medium_SSP5_relocation=lambda_medium_SSP5*(Percent_relocated[-1]*flooding_med_percent+(1-flooding_med_percent))
```

```{r Loss Simulation SSP5 with Relocation}
n=100000
stopping_time=10
count=0
yearlyloss=matrix(rep(0,(stopping_time+1)*n),nrow=stopping_time+1,ncol=n)
for(i in 1:stopping_time){
  yearlyloss[i+1,]=yearlyloss[i+1,]+yearlyloss[i,]
  for(j in 1:n){
    N_med=rpois(1,lambda_medium_SSP5_relocation[i])
    N_maj=rpois(1,lambda_major_SSP5_relocation[i])
    if(N_med>0){
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+sum(1.25*rinvgauss(N_med,invgauss_med_fit[1],invgauss_med_fit[2]))
    } 
    if(N_maj>0){
      temp_maj_cost=sum(2.25*rlgamma(N_maj,lgamma_maj_fit[1],lgamma_maj_fit[2]))
      yearlyloss[i+1,j]=yearlyloss[i+1,j]+temp_maj_cost+temp_maj_cost/median_house_price*2.5*1857.908671*12
    }
  }
  yearlyloss[i+1,]=yearlyloss[i+1,]+(-Percent_relocated[i+1]+Percent_relocated[i])*household_at_risk*median_house_price
}
quantile99_SSP5_relocation=rep(0,stopping_time+1)
quantile95_SSP5_relocation=rep(0,stopping_time+1)
quantile50_SSP5_relocation=rep(0,stopping_time+1)
quantile5_SSP5_relocation=rep(0,stopping_time+1)
quantile1_SSP5_relocation=rep(0,stopping_time+1)
sim_mean_SSP5_relocation=rep(0,stopping_time+1)
for(k in 1:(stopping_time+1)){
  quantile99_SSP5_relocation[k]=quantile(yearlyloss[k,],0.99)
  quantile95_SSP5_relocation[k]=quantile(yearlyloss[k,],0.95)
  quantile50_SSP5_relocation[k]=quantile(yearlyloss[k,],0.5)
  quantile5_SSP5_relocation[k]=quantile(yearlyloss[k,],0.05)
  quantile1_SSP5_relocation[k]=quantile(yearlyloss[k,],0.01)
  sim_mean_SSP5_relocation[k]=mean(yearlyloss[k,])
}
mean_damage=rep(0,11)
for(i in 1:10){
  mean_damage[i+1]=sum(expected_yearly_damage[1:i])
}

{plot(2020:2030,quantile99_SSP5_relocation,type="l",xlab="Years",ylab="Damage Cost (Ꝕ)")
polygon(c(2020:2030,2030:2020),c(quantile99_SSP5_relocation,rev(quantile95_SSP5_relocation)),col="lightcoral",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile95_SSP5_relocation,rev(quantile50_SSP5_relocation)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile50_SSP5_relocation,rev(quantile5_SSP5_relocation)),col="palegreen",border = "white")
polygon(c(2020:2030,2030:2020),c(quantile5_SSP5_relocation,rev(quantile1_SSP5_relocation)),col="lightcoral",border = "white")
#lines(2020:2030,mean_damage,type="l",lwd=4,col="blue")
lines(2020:2030,quantile99_SSP5_relocation,type="l",lwd=2)
lines(2020:2030,quantile95_SSP5_relocation,type="l",lwd=2)
lines(2020:2030,quantile50_SSP5_relocation,type="l",lwd=2)
lines(2020:2030,quantile5_SSP5_relocation,type="l",lwd=2)
lines(2020:2030,quantile1_SSP5_relocation,type="l",lwd=2)
lines(2020:2030,sim_mean_SSP5_relocation,type="l",lwd=4,col="blue")
}
quantile99_SSP5_relocation
sim_mean_SSP5_relocation
```
```{r Ruin Simulation}
set.seed(47)
n=100000 #number of simulations
#PI=1*expected_yearly_damage #rate of continuous payment
c_0=1500000000 #starting reserve
stopping_time=10 #number of periods (years)

count=0
for(j in 1:n){
  C_t_minus=c_0
  
{  
  #claim_t_minor=NULL
  claim_t_medium=NULL
  claim_t_major=NULL
  for(k in 1:stopping_time){
    #claim_t_minor=c(claim_t_minor,k-1+runif(rpois(1,lambda_minor[k]))) #generate claim arrival time for minor
    claim_t_medium=c(claim_t_medium,k-1+runif(rpois(1,lambda_medium_SSP5[k]))) #generate claim arrival time for medium
    claim_t_major=c(claim_t_major,k-1+runif(rpois(1,lambda_major_SSP5[k]))) #generate claim arrival time for major
  }
  #mmm_tags=c(rep("mi",length(claim_t_minor)),rep("me",length(claim_t_medium)),rep("ma",length(claim_t_major)))
  mmm_tags=c(rep("me",length(claim_t_medium)),rep("ma",length(claim_t_major)))
  #claim_t=c(claim_t_minor,claim_t_medium,claim_t_major)
  claim_t=c(claim_t_medium,claim_t_major)
  mmm_tags=c("NA",mmm_tags[order(claim_t)])
  claim_t=c(0,sort(claim_t))
}#Generate claim arrivals for minor, medium, major
  
  for(i in 1:(length(claim_t)-1)){
      C_t_minus=c(C_t_minus,C_t_minus[i]
                  +(floor(claim_t[i+1])-claim_t[i])*PI[floor(claim_t[i]+1)] #Note that this breaks if floor(claim_t[i+1])-floor(claim_t[i])>1 but this is way too unlikely for me to want to code the edge case
                  +(claim_t[i+1]-floor(claim_t[i+1]))*PI[floor(claim_t[i+1]+1)]#PI*(claim_t[i+1]-claim_t[i]) for constant PI
                  ##-(1-exp(claim_t[i+1]))*500000 RELOCATION COSTS
                  #-runif(1,0,2*2427.055)*(mmm_tags[i+1]=="mi") #distribution for minor
                  -rlnorm(1,lnorm_med_fit$estimate[1],lnorm_med_fit$estimate[2])
                  *(mmm_tags[i+1]=="me")*1.75
                  *(Discount_factor*(1-exp(claim_t[i+1]))) #distribution for medium
                  -rlgamma(1,lgamma_maj_fit$estimate[1],lgamma_maj_fit$estimate[2])
                  *(mmm_tags[i+1]=="ma")*2.25
                  *(Discount_factor*(1-exp(claim_t[i+1]))) #distribution for major
                  ) #GENERATING CLAIM AMOUNTS FOR EACH OF THE ARRIVAL TIMES
  }
  count=count+(min(C_t_minus)<0)  #CHECKING WHETHER RUIN OCCURED
}
count/n
```

```{r pressure, echo=FALSE}
plot(pressure)
```
```{r pressure, echo=FALSE}
plot(pressure)
```